/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import Header from './components/Header'
import MainContent from './components/MainContent'
import Footer from './components/Footer'

function App() {
  return (
    <div className='flex flex-col'>
      <Header />
      <MainContent />
      <Footer />
    </div>
  )
}

export default App
