/**
 * This code was generated by Builder.io.
 */
import React from 'react'

function DocumentSelector() {
  const documentTypes = ['Receipt', 'Invoice', 'W-2', 'W-9', 'Check', 'Bank Statement', 'Other Docs']

  return (
    <div className='flex flex-col justify-center p-px mt-8 w-full text-base leading-6 text-white rounded-lg border border-solid border-slate-500 max-md:max-w-full'>
      <div className='flex flex-wrap justify-center p-2 w-full max-md:max-w-full'>
        {documentTypes.map((type, index) => (
          <button
            key={index}
            className={`flex flex-col grow shrink justify-center px-3 whitespace-nowrap min-w-[92px] ${
              index === 0 ? 'text-slate-800 bg-white' : 'text-white'
            }`}
          >
            <div className='flex-1 shrink self-stretch px-12 py-3 w-full rounded-lg min-h-[48px] min-w-[80px] max-md:px-5'>
              {type}
            </div>
          </button>
        ))}
      </div>
    </div>
  )
}

export default DocumentSelector
