/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import DocumentSelector from './DocumentSelector'
import DocumentVisualizer from './DocumentVisualizer'

function DocumentProcessingDemo() {
  return (
    <section className='flex flex-col justify-center items-center px-16 py-24 w-full max-md:px-5 max-md:max-w-full'>
      <div className='flex flex-col justify-center px-40 w-full max-w-[1800px] max-md:px-5 max-md:max-w-full'>
        <div className='flex flex-col w-full max-md:max-w-full'>
          <div className='flex flex-col justify-center px-40 w-full text-center max-md:px-5 max-md:max-w-full'>
            <div className='flex flex-col w-full min-h-[314px] max-md:max-w-full'>
              <h2 className='flex flex-col w-full text-6xl leading-[64px] max-md:max-w-full'>
                <div className='flex relative flex-col px-2 w-full text-slate-800 max-md:max-w-full'>
                  <div className='z-0 self-center opacity-10 max-md:max-w-full max-md:text-4xl max-md:leading-[51px]'>
                    Process your docs in less time than it takes to <br /> read this.
                  </div>
                  <div className='absolute px-2 max-w-full w-[1192px] max-md:max-w-full max-md:text-4xl max-md:leading-[51px]'>
                    Process your docs in less time than it takes to <br /> read this.
                  </div>
                </div>
                <div className='flex flex-col px-96 mt-6 w-full max-md:px-5 max-md:max-w-full'>
                  <div className='bg-clip-text max-md:text-4xl'>See for yourself.</div>
                </div>
              </h2>
              <DocumentSelector />
            </div>
          </div>
          <DocumentVisualizer />
        </div>
      </div>
    </section>
  )
}

export default DocumentProcessingDemo
