/**
 * This code was generated by Builder.io.
 */
import React from 'react'

function DocumentVisualizer() {
  return (
    <div className='flex flex-col justify-center mt-10 w-full min-h-[880px] rounded-[40px] max-md:max-w-full'>
      <div className='flex overflow-hidden flex-col flex-1 w-full max-md:max-w-full'>
        <div className='flex overflow-hidden flex-col gap-6 p-6 w-full border border-solid bg-stone-200 bg-opacity-30 border-white border-opacity-30 min-h-[880px] rounded-[40px] max-md:px-5 max-md:max-w-full'>
          <div className='flex flex-col justify-center py-8 w-full border border-white border-dashed rounded-[40px] max-md:max-w-full'>
            <div className='flex flex-col max-md:max-w-full'>
              <div className='flex flex-col px-4 w-full max-w-[1474px] max-md:max-w-full'>
                <div className='flex flex-wrap justify-center items-center w-full px-[556px] max-md:px-5 max-md:max-w-full'>
                  <div className='flex flex-col grow shrink-0 items-start self-stretch pr-4 my-auto min-h-[32px] w-[38px]'>
                    <div className='flex overflow-hidden flex-col justify-center items-center w-8 min-h-[32px]'>
                      <img
                        loading='lazy'
                        src='https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/e5acf4f1fe918f2c4261956ae1a4a0fc0c57ca0f5df844cfc602adae68461552?apiKey=e4c57968c0bc4afc844f2d99ccd20654&'
                        alt=''
                        className='object-contain flex-1 w-full aspect-square'
                      />
                    </div>
                  </div>
                  <div className='flex flex-col grow shrink-0 self-stretch pb-1 my-auto text-white min-w-[240px] w-[273px]'>
                    <p className='w-full text-lg leading-5'>Drag or upload your document here</p>
                    <p className='mt-2.5 text-xs leading-3'>(JPEG, PNG or PDF)</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* Add more content for document visualization here */}
        </div>
      </div>
    </div>
  )
}

export default DocumentVisualizer
