/**
 * This code was generated by Builder.io.
 */
import React from 'react'

function FooterLogo() {
  return (
    <div className='flex flex-col grow shrink min-w-[240px] w-[336px]'>
      <div className='flex flex-col w-full'>
        <div className='flex flex-col max-w-full w-[147px]'>
          <img
            loading='lazy'
            src='https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/35cc1667bb1c588a8b696318b864497ca13f146101fed6b317a50fb22ac95915?apiKey=e4c57968c0bc4afc844f2d99ccd20654&'
            alt='Company Logo'
            className='object-contain w-full aspect-[3]'
          />
        </div>
        <address className='mt-6 text-sm leading-5 text-white not-italic'>
          Headquartered in the heart of Silicon Valley at: <br />
          210 S B St, San Mateo, CA 94401, California (PT)
        </address>
        <p className='mt-4 text-xs leading-4 text-stone-200'>Made with 💚 in California.</p>
      </div>
      <div className='flex flex-col mt-6 max-w-full w-[105px]'>
        <img
          loading='lazy'
          src='https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/0e83f04ead7e7f6ff7b409fdaefe8175e6445cb3f9792be6f94c03f2f2000007?apiKey=e4c57968c0bc4afc844f2d99ccd20654&'
          alt='Company Certification'
          className='object-contain w-full aspect-[1.46]'
        />
      </div>
    </div>
  )
}

export default FooterLogo
