/**
 * This code was generated by Builder.io.
 */
import React from 'react'

function FooterNavigation() {
  const navigationSections = [
    {
      title: 'Discover',
      links: ['Security', 'Videos', 'Free OCR Book', 'Developer SDKs', 'Careers'],
    },
    {
      title: 'Support',
      links: ['Talk To An Expert', 'Worldwide Coverage', 'Contact', 'FAQ', 'API Docs', 'Mobile Docs'],
    },
  ]

  return (
    <nav className='flex flex-col grow shrink min-w-[240px] w-[780px] max-md:max-w-full'>
      <div className='flex flex-wrap justify-center items-start w-full max-md:max-w-full'>
        {navigationSections.map((section, index) => (
          <div key={index} className='flex flex-col flex-1 shrink px-3 text-white basis-0'>
            <h3 className='text-base leading-6'>{section.title}</h3>
            <ul className='flex flex-col mt-10 w-full text-base leading-6 max-md:mt-10'>
              {section.links.map((link, linkIndex) => (
                <li key={linkIndex} className='flex relative flex-col mt-1 w-full'>
                  <a href='#' className='z-0'>
                    {link}
                  </a>
                  <div className='flex absolute left-0 bottom-0.5 z-0 w-0.5 h-px min-h-[1px] right-[190px]' />
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </nav>
  )
}

export default FooterNavigation
