/**
 * This code was generated by Builder.io.
 */
import React from 'react'

function FooterSocialLinks() {
  const socialLinks = [
    {
      name: 'LinkedIn',
      icon: 'https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/7e0d7f002264d2019c44f0f33bc74f1631fe8882f06dc7f872ffc0c5c5f6a82f?apiKey=e4c57968c0bc4afc844f2d99ccd20654&',
    },
    {
      name: 'X/Twitter',
      icon: 'https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/4e4004b77fe80c5e7217e9ec724e3f1007ca223d7695cf8eb984f671e0bc1a97?apiKey=e4c57968c0bc4afc844f2d99ccd20654&',
    },
    {
      name: 'YouTube',
      icon: 'https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/c8918100c5d935d3722d69c1ef01eb6f8aa6968b43b675094ad299cc41b43394?apiKey=e4c57968c0bc4afc844f2d99ccd20654&',
    },
  ]

  return (
    <div className='flex flex-col flex-1 shrink px-3 text-white whitespace-nowrap basis-0'>
      <h3 className='text-base leading-6'>Follow</h3>
      <ul className='flex flex-col mt-10 w-full text-base leading-6 max-md:mt-10'>
        {socialLinks.map((link, index) => (
          <li key={index} className='flex gap-10 justify-between items-center mt-1 w-full'>
            <a href='#' className='flex relative flex-col self-stretch my-auto'>
              <span className='z-0'>{link.name}</span>
              <div className='flex absolute bottom-0 left-0 z-0 w-px h-px min-h-[1px] right-[60px]' />
            </a>
            <img
              loading='lazy'
              src={link.icon}
              alt={`${link.name} icon`}
              className='object-contain shrink-0 self-stretch my-auto w-2 aspect-square'
            />
          </li>
        ))}
      </ul>
    </div>
  )
}

export default FooterSocialLinks
