/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import FooterLogo from './FooterLogo'
import FooterNavigation from './FooterNavigation'
import FooterSocialLinks from './FooterSocialLinks'
import FooterCTA from './FooterCTA'

function Footer() {
  return (
    <footer className='flex relative z-0 flex-col gap-20 items-center px-16 w-full bg-slate-800 pt-[600px] max-md:px-5 max-md:pt-24 max-md:max-w-full'>
      <div className='flex z-0 flex-wrap gap-10 justify-center px-6 pt-20 w-full max-w-[1800px] max-md:px-5 max-md:max-w-full'>
        <FooterLogo />
        <FooterNavigation />
        <FooterSocialLinks />
        <FooterCTA />
      </div>
      <div className='flex z-0 flex-col mt-20 w-full max-w-[1800px] max-md:mt-10 max-md:max-w-full'>
        <img
          loading='lazy'
          src='https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/5f665515e887fc7da54c67e7dcb68cfec37a1aef9728fdd0a0236c05354e573a?apiKey=e4c57968c0bc4afc844f2d99ccd20654&'
          alt=''
          className='object-contain w-full aspect-[2.97]'
        />
      </div>
      <div className='flex absolute inset-0 z-0 flex-col justify-center self-start w-full bg-slate-800 max-md:max-w-full'>
        <img
          loading='lazy'
          src='https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/cacdd235dfd0f7de165203366adac4fd232a42c6d908c4914143ca591fe5238f?apiKey=e4c57968c0bc4afc844f2d99ccd20654&'
          alt=''
          className='object-contain flex-1 w-full aspect-[1.12] max-md:max-w-full'
        />
      </div>
    </footer>
  )
}

export default Footer
