/**
 * This code was generated by Builder.io.
 */
import React from 'react'

function FooterCTA() {
  return (
    <div className='flex flex-col flex-1 shrink pl-3 basis-3'>
      <p className='w-full text-base leading-6 text-white'>
        Free 14-day trial, <br /> no credit card required.
      </p>
      <button className='flex flex-col mt-4 w-full text-base leading-4 text-center shadow-2xl bg-white bg-opacity-0 text-slate-800'>
        <div className='px-7 py-6 w-full rounded max-md:px-5'>Create Free Account</div>
      </button>
    </div>
  )
}

export default FooterCTA
