/**
 * This code was generated by Builder.io.
 */
import React from 'react'

function GetStartedButton() {
  return (
    <button className='flex flex-col self-stretch my-auto text-base leading-4 text-center text-slate-800 w-[175px]'>
      <div className='p-4 w-full rounded'>Get Started for Free</div>
    </button>
  )
}

export default GetStartedButton
