/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import Logo from './Logo'
import Navigation from './Navigation'
import LoginButton from './LoginButton'
import GetStartedButton from './GetStartedButton'

function Header() {
  return (
    <header className='flex absolute right-0 top-4 z-0 flex-col px-8 pt-4 w-[1920px] max-md:px-5 max-md:max-w-full'>
      <div className='flex relative justify-center items-start w-full pr-[552px] max-md:pr-5 max-md:max-w-full'>
        <Logo />
        <div className='flex absolute inset-x-0 z-0 shrink-0 h-px bg-zinc-300 bottom-[-30px] min-w-[240px] w-[1856px] max-md:max-w-full' />
        <Navigation />
        <div className='flex absolute right-0 bottom-0 z-0 gap-6 items-center h-12 min-h-[48px] min-w-[240px] w-[278px]'>
          <LoginButton />
          <GetStartedButton />
        </div>
      </div>
    </header>
  )
}

export default Header
