/**
 * This code was generated by Builder.io.
 */
import React from 'react'

function HeroImage() {
  return (
    <div className='flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full'>
      <div className='flex flex-col grow mt-0 max-md:-mt-44 max-md:max-w-full'>
        <div className='flex flex-col justify-center pb-28 w-full max-md:pb-24 max-md:max-w-full'>
          <div className='flex flex-col flex-1 justify-center py-16 w-full max-md:max-w-full'>
            <img
              loading='lazy'
              src='https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/0422aad50fe359d62b5a95ceb5e1a3c727c0552f7d3723ecffc8360fac208606?apiKey=e4c57968c0bc4afc844f2d99ccd20654&'
              alt='Hero visual'
              className='object-contain w-full aspect-[0.89] max-md:max-w-full'
            />
          </div>
        </div>
      </div>
    </div>
  )
}

export default HeroImage
