/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import HeroContent from './HeroContent'
import HeroImage from './HeroImage'

function Hero() {
  return (
    <section className='flex z-10 flex-col pb-52 w-full max-md:pb-24 max-md:max-w-full'>
      <div className='flex relative flex-col px-16 pt-96 w-full max-md:px-5 max-md:pt-24 max-md:max-w-full'>
        <div className='flex absolute inset-0 z-0 flex-col justify-center w-full bg-slate-800 max-md:max-w-full'>
          <img
            loading='lazy'
            src='https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/a003fd24e2a2aeb150c7f4987f028bce4209775684d10025efca0362c2972002?apiKey=e4c57968c0bc4afc844f2d99ccd20654&'
            alt='Background'
            className='object-contain flex-1 w-full aspect-[1.52] max-md:max-w-full'
          />
        </div>
        <div className='flex z-0 flex-col justify-center self-center px-40 w-full max-w-[1800px] max-md:px-5 max-md:max-w-full'>
          <div className='flex flex-col w-full min-h-[868px] max-md:max-w-full'>
            <div className='w-full max-md:pl-5 max-md:max-w-full'>
              <div className='flex gap-5 max-md:flex-col'>
                <HeroContent />
                <HeroImage />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

export default Hero
