/**
 * This code was generated by Builder.io.
 */
import React from 'react'

function HeroContent() {
  return (
    <div className='flex flex-col w-6/12 max-md:ml-0 max-md:w-full'>
      <div className='flex flex-col items-start w-full max-md:mt-6 max-md:max-w-full'>
        <h1 className='self-stretch text-6xl text-white leading-[64px] max-md:max-w-full max-md:text-4xl max-md:leading-10'>
          Process your docs in <br /> less time than it takes <br /> to read this.
        </h1>
        <p className='mt-8 max-w-full text-lg leading-6 text-white w-[516px] max-md:max-w-full'>
          Fast, accurate, and secure document capture and data extraction <br /> on any type of document. Say goodbye to
          lost users and business.
        </p>
        <div className='flex gap-1 mt-8 max-w-full leading-4 text-center w-[289px]'>
          <button className='p-4 text-base rounded text-slate-800 bg-white'>Get Started for Free</button>
          <button className='flex relative gap-4 items-start p-4 text-base text-white rounded'>
            <div className='flex absolute inset-0.5 z-0 shrink-0 h-11 rounded-sm border-2 border-white border-solid w-[107px]' />
            <span className='z-0'>Free Demo</span>
          </button>
        </div>
      </div>
    </div>
  )
}

export default HeroContent
