/**
 * This code was generated by Builder.io.
 */
import React from 'react'

function InsightCard({ image, category, title }) {
  return (
    <div className='flex flex-col grow shrink justify-center pr-6 min-w-[240px] w-[1216px] max-md:max-w-full'>
      <div className='flex-1 w-full'>
        <div className='flex flex-col grow min-h-[322px] max-md:mt-6 max-md:max-w-full'>
          <div className='flex overflow-hidden flex-col w-full rounded-lg max-md:max-w-full'>
            <div className='flex justify-center w-full max-md:max-w-full'>
              <img
                loading='lazy'
                src={image}
                alt={title}
                className='object-contain flex-1 shrink w-full aspect-[1.9] basis-0 max-w-[434px] min-w-[240px] max-md:max-w-full'
              />
            </div>
          </div>
          <div className='mt-2 w-full text-xs tracking-wide leading-relaxed text-green-500 max-md:max-w-full'>
            <span className='text-green-500'>[</span>
            <span className='text-slate-800'> {category} </span>
            <span className='text-green-500'>]</span>
          </div>
          <h3 className='overflow-hidden mt-2 w-full text-base leading-6 min-h-[43px] text-slate-800 max-md:max-w-full'>
            {title}
          </h3>
        </div>
      </div>
    </div>
  )
}

export default InsightCard
