/**
 * This code was generated by Builder.io.
 */
import React from 'react'

function LoginButton() {
  return (
    <button className='flex flex-col self-stretch my-auto w-10 text-base leading-6 whitespace-nowrap text-slate-800'>
      <div className='flex relative items-start w-full'>
        <span className='z-0'>Login</span>
        <div className='flex absolute left-0 bottom-0.5 z-0 shrink-0 w-px h-px right-[39px]' />
      </div>
    </button>
  )
}

export default LoginButton
