/**
 * This code was generated by Builder.io.
 */
import React from 'react'

function Logo() {
  return (
    <div className='flex z-0 items-center py-2 min-h-[48px] min-w-[240px] w-[352px]'>
      <div className='flex flex-col self-stretch my-auto w-[95px]'>
        <img
          loading='lazy'
          src='https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/2756e5fe606c0b242b27b83ec81006599220fde39b388eaa982118fd1fc62cf5?apiKey=e4c57968c0bc4afc844f2d99ccd20654&'
          alt='Company Logo'
          className='object-contain w-full aspect-[2.97]'
        />
      </div>
    </div>
  )
}

export default Logo
