/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import Hero from './Hero'
import TrustedOrganizations from './TrustedOrganizations'
import ModularPlatform from './ModularPlatform'
import DocumentProcessingDemo from './DocumentProcessingDemo'
import IndustryInsights from './IndustryInsights'

function MainContent() {
  return (
    <main className='flex flex-col'>
      <Hero />
      <TrustedOrganizations />
      <ModularPlatform />
      <DocumentProcessingDemo />
      <IndustryInsights />
      {/* Add other main content sections here */}
    </main>
  )
}

export default MainContent
