/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function ModuleCard({ title, features }) {
  return (
    <div className="flex flex-col grow shrink gap-8 p-3.5 rounded-xl border-black border-solid border-[3px] min-w-[240px] w-[396px] max-md:max-w-full">
      <h3 className="flex flex-col items-start w-full text-2xl leading-[64px] text-slate-800 max-md:max-w-full">
        {title}
      </h3>
      <ul className="flex flex-col pl-5 mt-8 w-full text-base leading-6 max-md:max-w-full">
        {features.map((feature, index) => (
          <li key={index} className="flex relative flex-col items-start w-full max-md:max-w-full">
            <span className="text-slate-800">{feature}</span>
            <div className="absolute bottom-0 -left-4 z-0 w-4 h-6 text-green-500">•</div>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default ModuleCard;