/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import ModuleCard from './ModuleCard'

function ModularPlatform() {
  const modules = [
    {
      title: 'Document Capture',
      features: ['Lens for Mobile', 'Lens for Browser', 'Lens for Credit Cards', 'WhatsApp Loyalty Chatbot'],
    },
    {
      title: 'Data Extraction',
      features: [
        'Receipts OCR API',
        'Invoices OCR API',
        'Bank Checks OCR API',
        'Bank Statements OCR API',
        'W2 OCR API',
        '∀Docs LLM API (other docs)',
      ],
    },
    {
      title: 'Data Services',
      features: ['Fraud Detection', 'Product Matching', 'Business Rules Engine', 'PDF Content Splitter'],
    },
  ]

  return (
    <section className='flex flex-col items-center px-16 pt-24 pb-40 w-full max-md:px-5 max-md:pb-24 max-md:max-w-full'>
      <div className='flex flex-col justify-center px-40 w-full max-w-[1800px] max-md:px-5 max-md:max-w-full'>
        <div className='flex flex-col w-full min-h-[412px] max-md:max-w-full'>
          <h2 className='flex flex-col w-full text-6xl text-center leading-[64px] text-slate-800 max-md:max-w-full'>
            <div className='px-52 max-md:px-5 max-md:max-w-full max-md:text-4xl'>
              A Modular Platform with Powerful AI Tools
            </div>
          </h2>
          <div className='flex flex-wrap justify-center items-center mt-8 w-full text-base text-center h-[18px] px-[589px] text-slate-800 max-md:px-5 max-md:max-w-full'>
            <p className='self-stretch my-auto leading-6'>Explore the modules below or</p>
            <button className='self-stretch px-4 py-5 my-auto leading-4 rounded bg-white text-slate-800'>
              Start Trial
            </button>
          </div>
          <div className='flex flex-wrap gap-1.5 justify-center mt-8 w-full max-md:max-w-full'>
            {modules.map((module, index) => (
              <ModuleCard key={index} title={module.title} features={module.features} />
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}

export default ModularPlatform
