/**
 * This code was generated by Builder.io.
 */
import React from 'react'

function TrustedOrganizations() {
  const organizations = [
    {
      src: 'https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/701480b1b3a37d33916564be2d43bb6216dbb51d4169e58e7b2be644859ff873?apiKey=e4c57968c0bc4afc844f2d99ccd20654&',
      alt: 'Organization 1',
      width: '123px',
    },
    {
      src: 'https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/56f6aefaa0f7ca8585246df963f833fc86589f05ec2c6e6013db4a3e402a7622?apiKey=e4c57968c0bc4afc844f2d99ccd20654&',
      alt: 'Organization 2',
      width: '239px',
    },
    {
      src: 'https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/95acd20378a14dd2018703d3a696596f96d9b2ea49c1ccc86b51ef159ee51ca2?apiKey=e4c57968c0bc4afc844f2d99ccd20654&',
      alt: 'Organization 3',
      width: '192px',
    },
    {
      src: 'https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/fe47fcc2e998f1c41a175930b8eba03e10c495368a86bb3b4e51f0351a89fb69?apiKey=e4c57968c0bc4afc844f2d99ccd20654&',
      alt: 'Organization 4',
      width: '192px',
    },
    {
      src: 'https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/1fe06e84ffa59fc5e72da93ee7886eb7706d3e61b72614f38f108f3d4b5372eb?apiKey=e4c57968c0bc4afc844f2d99ccd20654&',
      alt: 'Organization 5',
      width: '258px',
    },
    {
      src: 'https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/b1a9abfe492f41b4d1fa1e6b60bbede0622e12627e166117147dc170e5b68b78?apiKey=e4c57968c0bc4afc844f2d99ccd20654&',
      alt: 'Organization 6',
      width: '183px',
    },
    {
      src: 'https://cdn.builder.io/api/v1/image/assets/e4c57968c0bc4afc844f2d99ccd20654/69cd63d2b7adecad80ca1ff5914bb505f59059ded46905b5c462a4899ba1bdad?apiKey=e4c57968c0bc4afc844f2d99ccd20654&',
      alt: 'Organization 7',
      width: '210px',
    },
  ]

  return (
    <section className='flex flex-col items-center px-16 mt-16 w-full max-md:px-5 max-md:mt-10 max-md:max-w-full'>
      <div className='flex flex-col justify-center px-40 w-full max-w-[1800px] max-md:px-5 max-md:max-w-full'>
        <div className='flex flex-col w-full min-h-[230px] max-md:max-w-full'>
          <h2 className='flex flex-col w-full text-4xl leading-10 text-center text-white min-w-[420px] max-md:max-w-full'>
            <div className='px-96 max-md:px-5 max-md:max-w-full'>Trusted by the world's leading organizations</div>
          </h2>
          <div className='flex flex-col px-20 pt-8 w-full max-md:px-5 max-md:max-w-full'>
            <div className='flex flex-wrap justify-center'>
              {organizations.map((org, index) => (
                <div key={index} className='flex flex-col justify-center p-2.5 min-h-[80px]'>
                  <div className='flex overflow-hidden flex-col max-w-full min-h-[60px]' style={{ width: org.width }}>
                    <div className='flex overflow-hidden flex-col justify-center items-center p-2.5 w-full min-h-[60px]'>
                      <img loading='lazy' src={org.src} alt={org.alt} className='object-contain w-full aspect-[2.6]' />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

export default TrustedOrganizations
